export const API_URL = "http://localhost:8080";

export const thunkOrderTypes = {
    CREATE_BILL: "CREATE_BILL",
    UPDATE_BILL: "UPDATE_BILL",
    GETALL_BILL: "GETALL_BILL",
    DELETE_BILL: "DELETE_BILL",
}

export const thunkDeliveryTypes = {
    CREATE_DELIVERY: "CREATE_DELIVERY",
    UPDATE_DELIVERY: "UPDATE_DELIVERY",
    GETALL_DELIVERY: "GETALL_DELIVERY",
    DELETE_DELIVERY: "DELETE_DELIVERY",
    GET_DELIVERY: "GET_DELIVERY",
}